# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('to_watch', models.NullBooleanField()),
                ('already_watched', models.NullBooleanField()),
                ('type', models.TextField(blank=True, null=True)),
                ('disk', models.CharField(blank=True, max_length=100, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='directories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('directory', models.TextField()),
                ('extension', models.CharField(max_length=5)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('md5', models.TextField(blank=True, null=True)),
                ('duration', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('a_codec', models.TextField(blank=True, null=True)),
                ('v_codec', models.TextField(blank=True, null=True)),
                ('props', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
