# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmediastreamer', '0002_mediafilelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilelog',
            name='last_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
