# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmediastreamer', '0005_mediafilelog_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='vp8_crf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
