# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djmediastreamer', '0007_subtitlesfile_subtitlesline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitlesfile',
            name='mediafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='djmediastreamer.MediaFile'),
        ),
        migrations.AlterField(
            model_name='subtitlesline',
            name='index',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
